Salesforce/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <description>Objeto para guardar los request y responses de los servicios</description>
    <label>Integration Log</label>
    <nameField>
        <label>Integration Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Integration_Log__c/fields/code__c.field-meta.xml
<CustomField>
    <fullName>code__c</fullName>
    <label>code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Integration_Log__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <description>Service Url Location</description>
    <inlineHelpText>Service Url Location</inlineHelpText>
    <label>EndPoint</label>
    <type>Url</type>
</CustomField>

Salesforce/main/default/objects/Integration_Log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Salesforce/main/default/objects/Integration_Log__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <description>En este campo se guarda el response del servicio</description>
    <label>Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Salesforce/main/default/objects/Integration_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Aquí se guarda el estado de la respuesta del servicio</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Alert</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Integration_Log__c/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <label>type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>InsertError</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>UpsertError</fullName>
            </value>
            <value>
                <fullName>ParserError</fullName>
            </value>
            <value>
                <fullName>ServiceError</fullName>
            </value>
            <value>
                <fullName>Not Found</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/classes/IntegrationLogUtils.cls
public class IntegrationLogUtils {
	
    /*IntegrationLogUtils.insertIntegrationServiceLog(request, response, endpoint)*/
    public static void insertIntegrationServiceLog(HttpRequest request, HttpResponse response, String endpoint,String documentId,String message){
        Integration_Log__c intLog = new Integration_Log__c();
        String body = response.getBody();
        String requestAsString = '';
        Map<String, Object> parsedResponse = new Map<String, Object>();
        parsedResponse = (Map<String, Object>) JSON.deserializeUntyped(body);
          if (request != null) {
                requestAsString = 'Method: ' + request.getMethod() + '\n' +
                                  /*'URL: ' + request.getUrl() + '\n' +
                                  'Headers: ' + String.join(new List<String>(request.getHeaders().keySet()), ', ') + '\n' +*/
                                  'Body: ' + request.getBody();
           }
        intLog.Request__c = requestAsString; //TODO AGREGAR FUNCION PARA REQUEST
        intLog.EndPoint__c = endpoint;
        intLog.Response__c = getResponseFromHttpResponse(response);
       // intLog.Type__c = 'ServiceError'; 
        //intLog.Status__c = 'Alert';
        intLog.code__c = String.valueOf(parsedResponse.get('code'));
        if((String)parsedResponse.get('type')!='Not Found'){
            intLog.type__c = (String)parsedResponse.get('type');
        }else{
            intLog.type__c = 'ServiceError';
        }
        intLog.Status__c = 'Warning';
        intLog.Comments__c = (String)parsedResponse.get('detail');
        intLog.message__c = message;
        insert intLog;
    }
    
    public static String getResponseFromHttpResponse(HttpResponse res){
        return 'Status Code response='+res.getStatusCode()+' / '+
            ' Body response='+res.getBody() + 
            ' / HeaderKeys' + res.getHeaderKeys() + 
            ' / Status' + res.getStatus();
    }
    
    public static void insertIntegrationDMLLog(){
        Integration_Log__c intLog = new Integration_Log__c();
        //INSERTAR UN LOG DE ERROR DE DML INSERT O UPDATE
        insert intLog;
    }
        public static void getIntegrationLogFromAccount(Map<String, Object> Logs){
        Integration_Log__c intLog = new Integration_Log__c();
        intLog.code__c = 'Map';
        if((String)logs.get('type')!=null){
             intLog.Type__c = (String)logs.get('type');    
        }else{
            intLog.Type__c = 'ServiceError'; 
        }
        intLog.Status__c = 'Warning';
        intLog.Comments__c = 'Mapping error';
        intLog.message__c = (String)logs.get('message');
        insert intLog;
        //return intLog;
    }
}